plugins {
    alias(libs.plugins.kotlin.jvm)
}

dependencies {
    api(project(":page:core"))
    api(project(":shared-core"))
    implementation("io.github.bonede:tree-sitter:0.26.3")
    implementation("io.github.bonede:tree-sitter-java:0.23.5")
    implementation("io.github.bonede:tree-sitter-kotlin:0.3.8.1")
    implementation("io.github.bonede:tree-sitter-python:0.25.0")
    implementation("io.github.bonede:tree-sitter-javascript:0.25.0")
    implementation("io.github.bonede:tree-sitter-typescript:0.23.2")
    implementation("io.github.bonede:tree-sitter-go:0.25.0")
    implementation("io.github.bonede:tree-sitter-rust:0.24.0")
    implementation("io.github.bonede:tree-sitter-c:0.24.1")
    implementation("io.github.bonede:tree-sitter-cpp:0.23.4")
    implementation("io.github.bonede:tree-sitter-ruby:0.23.1")
    implementation("io.github.bonede:tree-sitter-bash:0.25.1")
    implementation("io.github.bonede:tree-sitter-html:0.23.2")
    implementation("io.github.bonede:tree-sitter-css:0.25.0")
    implementation("io.github.bonede:tree-sitter-json:0.24.8")
    implementation("io.github.bonede:tree-sitter-yaml:0.5.0a")
    implementation("io.github.bonede:tree-sitter-lua:2.1.3a")
    implementation("io.github.bonede:tree-sitter-swift:0.5.0")
    implementation("io.github.bonede:tree-sitter-scala:0.24.0")
    implementation("io.github.bonede:tree-sitter-haskell:0.23.1")
    implementation("io.github.bonede:tree-sitter-ocaml:0.23.2")
    implementation("io.github.bonede:tree-sitter-elixir:0.2.0")
    implementation("io.github.bonede:tree-sitter-clojure:0.0.12a")
    implementation("io.github.bonede:tree-sitter-perl:1.1.0")
    implementation("io.github.bonede:tree-sitter-r:main-a")
    implementation("io.github.bonede:tree-sitter-php:0.24.2")
    implementation("io.github.bonede:tree-sitter-sql:gh-pages-a")
    implementation("io.github.bonede:tree-sitter-markdown:0.7.1a")
    implementation("io.github.bonede:tree-sitter-dart:master-a")
    implementation("io.github.bonede:tree-sitter-zig:main-a")
    implementation("io.github.bonede:tree-sitter-dockerfile:0.2.0")
    implementation("io.github.bonede:tree-sitter-vue:0.2.1a")
    implementation("io.github.bonede:tree-sitter-svelte:0.11.0a")
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}
